################################################################################
# Node-RED Stack or Compose
################################################################################
# Docker commands
#   Daemon pigpiod - Link: https://hub.docker.com/r/zinen2/alpine-pigpiod
#     docker run -it -p 8888:8888 --privileged zinen2/alpine-pigpiod:arm64v8
#   Daemon node-red
#     docker run -p 51880:1880 -v /home/pi/Code/ACM/Docker/node-red/data:/data --name mynodered nodered/node-red
#
# docker-compose -f docker-nodered-influxdb-pigpiod.yml --env-file ./../.env up -d
################################################################################
version: "3.7"

services:
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: always
    ports:
      - "51880:1880"
    networks:
      - iot-net
    volumes:
      - /home/pi/Code/ACM/Docker/node-red/data:/data
    depends_on:
      influxdb2:
        condition: service_healthy

  influxdb2:
    image: influxdb:latest
    container_name: influxdb2
    restart: always
    ports:
      - 8086:8086
    networks:
      - iot-net
    volumes:
      - type: bind
        source: /home/pi/Code/ACM/Docker/influxdb2/data
        target: /var/lib/influxdb2
      - type: bind
        source: /home/pi/Code/ACM/Docker/influxdb2/config
        target: /etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDBUSER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDBPASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=SET 
      - DOCKER_INFLUXDB_INIT_BUCKET=rpi-os
    healthcheck:
      test: "curl --fail http://localhost:8086/ping"
      interval: 60s
      retries: 5
      start_period: 30s
      timeout: 10s

  pigpiod:
    image: zinen2/alpine-pigpiod:arm64v8
    container_name: pigpiod
    privileged: true
    restart: always
    ports:
      - "8888:8888"
    networks:
      - iot-net

networks:
  iot-net:
    driver: bridge
    ipam:
      driver: default
      config:
        # This will assign ip 172.30.0.1 to host.
        - subnet: "172.30.0.0/24"